INSERT INTO produkt (nazev,id_znacka) VALUES
('Lifebar červená řepa RAW BIO 47 g','8'),
('Lifebar třešňová RAW BIO 47 g','8'),
('Lifebar fíková RAW BIO 47 g','8'),
('Lifebar čokoládová RAW BIO 47 g','8'),
('Lifebar čokoládová RAW BIO 25 g','8'),
('Lifebar kokosová RAW BIO 47 g','8'),
('Lifebar kokosová RAW BIO 25 g','8'),
('Lifebar meruňková RAW BIO 47 g','8'),
('Lifebar brazilská RAW BIO 47 g','8'),
('Lifebar brazilská RAW BIO 25 g','8'),
('Lifebar karobová s lískovými oříšky RAW BIO 47 g','8'),
('Lifebar jablečná RAW BIO 47 g','8'),
('Lifebar jablečná RAW BIO 25 g','8'),
('Lifebar InChoco  švestka RAW BIO 40 g','8'),
('Lifebar InChoco  pomeranč RAW BIO 40 g','8'),
('Lifebar InChoco  Cacao Vanilla RAW BIO 40 g','8'),
('Lifebar Protein  Wild Berry RAW BIO 47 g','8'),
('Lifebar Protein  Nuts&Vanilla RAW BIO 47 g','8'),
('Lifebar Protein  Strawberry RAW BIO 47 g','8'),
('Lifebar Protein  Raspberry RAW BIO 47 g','8'),
('Lifebar Protein  Chocolate Green RAW BIO 47 g','8'),
('Lifebar Superfoods  Maca Baobab RAW BIO 47 g','8'),
('Lifebar Superfoods  Brazil Guarana RAW BIO 47 g','8'),
('Lifebar Superfoods  Chia Pistachio RAW BIO 47 g','8'),
('Lifebar Superfoods  Blueberry Quinoa RAW BIO 47 g','8'),
('Lifebar Superfoods  Acai Banana RAW BIO 47 g','8'),
('Hemp & Fig BIO 48 g','9'),
('Hemp & Cocoa BIO 48 g','9'),
('Hemp & Black Sesame BIO 48 g','9'),
('Hemp & Sour Cherry BIO 48 g','9'),
('Hemp & Cranberry BIO 48 g','9'),
('Hemp & Mango & Sea Buckthorn BIO 48 g','9'),
('Raspberry & Almond BIO 42 g','10'),
('Chocolate & Walnut BIO 42 g','10'),
('Liquorice & Almond BIO 42 g','10'),
('Caramel & Hazelnut BIO 42 g','10'),
('No-Bake White Chocolate Blueberry Crumble BIO 35 g','10'),
('No-Bake Apple Crumble BIO 35 g','10'),
('No-Bake Banana M*lk Chocolate Crumble BIO 35 g','10'),
('No-Bake Chocolate Crumble BIO 35 g','10'),
('No-Bake Raspberry Crumble BIO 35 g','10'),
('Handmade Swedish Chocolate Ball BIO 25 g','10'),
('Handmade Swedish Cinnamon Bun Ball BIO 25 g','10'),
('Handmade Swedish Lemon Cake Ball BIO 25 g','10');